# Generated by Django 4.1 on 2024-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='pet_genre',
            field=models.IntegerField(choices=[(1, '犬'), (2, '猫'), (3, '鳥'), (4, 'ウサギ'), (5, '爬虫類')], default=1),
        ),
    ]
