# Generated by Django 4.1 on 2024-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_category', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments_images/'),
        ),
    ]
