# Generated by Django 4.1 on 2024-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_location_users_bio_users_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pet',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '犬'), (2, '猫'), (3, '鳥'), (4, 'ウサギ'), (5, '爬虫類')], null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
