# Generated by Django 4.1 on 2024-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pet_remove_users_pet_users_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'オス'), (2, 'メス')], default=1)),
                ('genre', models.IntegerField(choices=[(1, '犬'), (2, '猫'), (3, '鳥類'), (4, '齧歯類'), (5, '爬虫類')], default=1)),
                ('breed', models.CharField(max_length=100)),
                ('petpicture', models.FileField(blank=True, null=True, upload_to='pet_pictures/')),
                ('characteristic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.AlterField(
            model_name='users',
            name='pet',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.pets'),
        ),
    ]
