# Generated by Django 4.1 on 2024-08-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_pets_pet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Pets',
        ),
    ]
