# Generated by Django 4.1 on 2024-08-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_pet_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='pet',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.petgenre'),
        ),
    ]
