# Generated by Django 4.1 on 2024-08-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_petgenre_alter_users_pet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetGenre',
            new_name='Pet',
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
