# Generated by Django 4.1 on 2024-08-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_pet_users_like_pet_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='like_pet',
            new_name='pet',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
