# Generated by Django 4.1 on 2024-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_like_pet_users_pet_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
