# Generated by Django 4.1 on 2024-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_pet_age_pet_picture_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pet_pictures/'),
        ),
    ]
