# Generated by Django 4.1 on 2024-08-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_pet_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorite_animals',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
