# Generated by Django 4.1 on 2024-08-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_users_favorite_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='characteristic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='genre',
            field=models.CharField(choices=[('1', '犬'), ('2', '猫'), ('3', '鳥類'), ('4', '齧歯類'), ('5', '爬虫類')], default='1', max_length=10),
        ),
    ]
